### ISSUE TITLE
"no module name 'toga_chart' " error when using briefcase run eventought it is present app_package and specified as a dependency.

### ISSUE THREAD

**Issue by MaxenceBraghetto** [beeware/toga-chart#15]
**Describe the bug**
I made a toga app using toga_chart install from this repo. It ran fine whith briefcase dev, bun when i use briefcase create then briefcase run i get an "ModuleNotFoundError: No module named 'toga_chart'" eventough i specified toga_chart as a dependency in the pyproject.toml file and briefcase create tells me that it has been installed. I also went and check inside the appimage directory to see if i could install it manually but it is already there in the app_packages directory along with the other modules. It happens wether i write 'toga-chart' directly as a dependecy or use git+the url of this repo. 

my current requires:
requires = ['git+https://github.com/beeware/toga-chart.git']

the error when running briefcase run:
[hellocucks] Starting app...

APPDIR IS /tmp/.mount_hello_yJEs6N
PYTHONPATH IS /tmp/.mount_hello_yJEs6N/usr/app:/tmp/.mount_hello_yJEs6N/usr/app_packages
PATH IS /opt/miniconda3/condabin:/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
Traceback (most recent call last):
  File "/tmp/.mount_hello_yJEs6N/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_hello_yJEs6N/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_hello_yJEs6N/usr/app/hellocucks/__main__.py", line 1, in <module>
    from hellocucks.app import main
  File "/tmp/.mount_hello_yJEs6N/usr/app/hellocucks/app.py", line 8, in <module>
    from toga_chart import Chart
ModuleNotFoundError: No module named 'toga_chart'

briefcase create log:
Application hellocucks already exists; overwrite [y/N]? y

[hellocucks] Removing old application bundle...

[hellocucks] Generating application template...
Using app template: https://github.com/beeware/briefcase-linux-appimage-template.git, branch 3.10
Using existing template (sha 4a41879ca392778895e7edb6e46c957be0457042, updated Sun Nov 14 09:53:59 2021)

[hellocucks] Installing support package...
Using support package https://briefcase-support.org/python?platform=linux&version=3.10&arch=x86_64
... using most recent revision
Python-3.10-linux-x86_64-support.b1.tar.gz already downloaded
Unpacking support package...

[hellocucks] Installing dependencies...
[hellocucks] Entering Docker context...

[hellocucks] Building Docker container image...

Sending build context to Docker daemon  522.8kB
Step 1/18 : FROM ubuntu:18.04
 ---> 5a214d77f5d7
Step 2/18 : WORKDIR /app
 ---> Using cache
 ---> d5c1146ad97c
Step 3/18 : ARG PY_VERSION
 ---> Using cache
 ---> 67ad6f688b9a
Step 4/18 : ARG SYSTEM_REQUIRES
 ---> Using cache
 ---> 50adf7b1196f
Step 5/18 : ENV DEBIAN_FRONTEND="noninteractive"
 ---> Using cache
 ---> 74508305b775
Step 6/18 : RUN apt-get update -y &&     apt-get install -y         software-properties-common         dirmngr         apt-transport-https         lsb-release         ca-certificates
 ---> Using cache
 ---> c479691fc39c
Step 7/18 : RUN apt-add-repository ppa:deadsnakes/ppa
 ---> Using cache
 ---> b57331b34e07
Step 8/18 : RUN apt-get update -y &&     apt-get install -y         git         python${PY_VERSION}-dev         python${PY_VERSION}-venv         ${SYSTEM_REQUIRES}
 ---> Using cache
 ---> 5e7565cc83ac
Step 9/18 : RUN python${PY_VERSION} -m ensurepip
 ---> Using cache
 ---> aa42fb48f3fb
Step 10/18 : RUN python${PY_VERSION} -m pip config set global.cache-dir false
 ---> Using cache
 ---> d165432d5e7e
Step 11/18 : RUN python${PY_VERSION} -m pip install --upgrade pip
 ---> Using cache
 ---> 279b3cb79c22
Step 12/18 : RUN python${PY_VERSION} -m pip install --upgrade setuptools
 ---> Using cache
 ---> 5924d0903b1e
Step 13/18 : RUN python${PY_VERSION} -m pip install --upgrade wheel
 ---> Using cache
 ---> f407b01385fa
Step 14/18 : ARG HOST_UID
 ---> Using cache
 ---> f8de1f8f7d2a
Step 15/18 : ARG HOST_GID
 ---> Using cache
 ---> 0e3ebccc7460
Step 16/18 : RUN groupadd --non-unique --gid $HOST_GID briefcase
 ---> Using cache
 ---> 6a280c8b5efa
Step 17/18 : RUN useradd --non-unique --uid $HOST_UID --gid $HOST_GID brutus --home /home/brutus
 ---> Using cache
 ---> 314ed5dce975
Step 18/18 : USER brutus
 ---> Using cache
 ---> 773f3f9a2c7a
Successfully built 773f3f9a2c7a
Successfully tagged briefcase/based.gov.hellocucks:py3.10
Collecting git+https://github.com/beeware/toga-chart.git
  Cloning https://github.com/beeware/toga-chart.git to /tmp/pip-req-build-tz_h3zb3
  Running command git clone --filter=blob:none -q https://github.com/beeware/toga-chart.git /tmp/pip-req-build-tz_h3zb3
  Resolved https://github.com/beeware/toga-chart.git to commit 085821daea1656a6cbf53af1a0fa9dc3766cd441
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting toga-gtk>=0.3.0.dev20
  Using cached toga_gtk-0.3.0.dev29-py3-none-any.whl (49 kB)
Collecting toga>=0.3.0.dev22
  Using cached toga-0.3.0.dev29-py3-none-any.whl (4.0 kB)
Collecting matplotlib>=3.0.3
  Using cached matplotlib-3.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.9 MB)
Collecting gbulb>=0.5.3
  Using cached gbulb-0.6.2-py2.py3-none-any.whl (17 kB)
Collecting pygobject>=3.14.0
  Using cached PyGObject-3.42.0-cp310-cp310-linux_x86_64.whl
Collecting toga-core==0.3.0.dev29
  Using cached toga_core-0.3.0.dev29-py3-none-any.whl (488 kB)
Collecting pycairo>=1.17.0
  Using cached pycairo-1.20.1-cp310-cp310-linux_x86_64.whl
Collecting travertino>=0.1.3
  Using cached travertino-0.1.3-py3-none-any.whl (15 kB)
Collecting numpy>=1.17
  Using cached numpy-1.21.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.6-py3-none-any.whl (97 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-8.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.2-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.28.5-py3-none-any.whl (890 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: toga-chart
  Building wheel for toga-chart (pyproject.toml) ... done
  Created wheel for toga-chart: filename=toga_chart-0.1.0-py3-none-any.whl size=5863 sha256=b06b46f712b9754149bc2162b38616c1b7f2b2a75b849a46e00aad5c05ba90aa
  Stored in directory: /tmp/pip-ephem-wheel-cache-yivrihpc/wheels/cf/c2/3f/c73e7fab5bd1b837af0903b96aef4d9240c7569c1202ff9c14
Successfully built toga-chart
Installing collected packages: pycairo, travertino, pygobject, toga-core, six, pyparsing, gbulb, toga-gtk, python-dateutil, pillow, packaging, numpy, kiwisolver, fonttools, cycler, toga, matplotlib, toga-chart
Successfully installed cycler-0.11.0 fonttools-4.28.5 gbulb-0.6.2 kiwisolver-1.3.2 matplotlib-3.5.1 numpy-1.21.5 packaging-21.3 pillow-8.4.0 pycairo-1.20.1 pygobject-3.42.0 pyparsing-3.0.6 python-dateutil-2.8.2 six-1.16.0 toga-0.3.0.dev29 toga-chart-0.1.0 toga-core-0.3.0.dev29 toga-gtk-0.3.0.dev29 travertino-0.1.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[hellocucks] Leaving Docker context.

[hellocucks] Installing application code...
Installing src/hellocucks...

[hellocucks] Installing application resources...
Unable to find src/hellocucks/resources/hellocucks-16.png for 16px application icon; using default
Unable to find src/hellocucks/resources/hellocucks-32.png for 32px application icon; using default
Unable to find src/hellocucks/resources/hellocucks-64.png for 64px application icon; using default
Unable to find src/hellocucks/resources/hellocucks-128.png for 128px application icon; using default
Unable to find src/hellocucks/resources/hellocucks-256.png for 256px application icon; using default
Unable to find src/hellocucks/resources/hellocucks-512.png for 512px application icon; using default

[hellocucks] Created linux/appimage/hello cucks

**To Reproduce**
1 - create a beeware app using toga_chart
2 - include toga chart in your apps requirement
3 - run briefcase create then briefcase run

**Environment:**
 - OS: artix linux

**Comment by MaxenceBraghetto** [comment]
sorry im retarded i forgot to run briefcase build everytime
